/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
	  extend: {
		colors: {
		  // Core Brand Colors
		  primary: '#FF8C00',
		  'light-bg': '#FFFAFA',
		  'dark-bg': '#111827',
		  
		  // Typography Colors
		  'light-text': {
			primary: '#1F2937',
			secondary: '#4B5563'
		  },
		  'dark-text': {
			primary: '#FFFFFF',
			secondary: '#9CA3AF'
		  },
		  
		  // Surface Colors
		  surface: {
			light: '#FFFFFF',
			'light-hover': '#F3F4F6',
			dark: '#1F2937',
			'dark-hover': '#374151'
		  },
		  
		  // Feedback Colors
		  feedback: {
			success: '#10B981',
			error: '#EF4444',
			warning: '#F59E0B',
			info: '#3B82F6'
		  },
		  
		  // Interactive States
		  'primary-hover': '#F87B16',
		  'primary-active': '#E67200',
		  border: {
			light: '#E5E7EB',
			dark: '#374151'
		  }
		}
	  }
	}
  }

//   Generated by Claude Sonnet 3.5