/** @type {import('tailwindcss').Config} */
export default {
	content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
	darkMode: "class",
	theme: {
		extend: {
			colors: {
				// Core Brand Colors
				primary: "#FF8C00",
				lightBg: "#FFFAFA",
				darkBg: "#111827",
				cardLightBg: "#FFFFFF",
				cardDarkBg: "#000000",

				// Typography Colors
				lightTextPrimary: "#1F2937",
				lightTextSecondary: "#4B5563",
				darkTextPrimary: "#FFFFFF",
				darkTextSecondary: "#9CA3AF",

				// Surface Colors
				surfaceLight: "#FFFFFF",
				surfaceLightHover: "#F3F4F6",
				surfaceDark: "#1F2937",
				surfaceDarkHover: "#374151",

				// Interactive States
				primaryHover: "#F87B16",
				borderLight: "#E5E7EB",
				borderDark: "#374151",
			},
		},
	},
	plugins: [require("@tailwindcss/typography")],
};

//	Generated by Claude Sonnet 3.5
